/**
 * The carrier's load offer (/t/…) in the carrier's language: Spanish for a Mexican carrier, English otherwise,
 * with ?lang= to switch. Plain words a dispatcher on a phone reads at a glance.
 */
export type Lang = "en" | "es";

export const TENDER_COPY = {
  en: {
    offer: "load offer",
    leg: { mx: "Mexico leg", ca: "Canada leg", crossing: "Border crossing", us: "US leg", domestic: "Domestic", equipment_move: "Equipment move" } as Record<string, string>,
    openUntil: "Open until",
    accepted: "Accepted",
    declined: "Declined",
    expired: "Expired",
    withdrawn: "Withdrawn",
    rateTbc: "Rate to be confirmed",
    pickup: "Pickup",
    delivery: "Delivery",
    asap: "ASAP",
    by: "by",
    pickupNo: "Pickup #",
    deliveryNo: "Delivery #",
    instructions: "Instructions",
    equipment: "Equipment",
    reference: "Reference",
    leg_: "leg",
    commodity: "Commodity",
    pieces: "Pieces",
    weight: "Weight",
    hazmat: "Hazmat",
    cargo: "Cargo",
    fromDispatch: "From dispatch",
    thanks: "Thank you — it's yours.",
    acceptedBy: (who: string, when: string, driver: string, unit: string | null, caja: string | null) => `Accepted by ${who} on ${when}. Driver ${driver}${unit ? `, unit ${unit}` : ""}${caja ? `, trailer ${caja}` : ""}. Dispatch will send pickup details.`,
    closed: "This offer is closed.",
    expiredText: "The deadline passed. Call dispatch if you can still cover it.",
    declinedBy: (who: string) => `Declined by ${who}.`,
    withdrawnText: "Dispatch withdrew it.",
    switchTo: "Ver en español",
    // form
    canYou: (c: string) => `${c}, can you cover this?`,
    yes: "Yes, accept",
    no: "No, decline",
    whoDrives: "Accept — who's driving?",
    why: "Decline — why?",
    yourName: "Your name",
    driverName: "Driver name",
    driverPhone: "Driver phone",
    unit: "Unit #",
    plates: "Unit plates",
    trailer: "Trailer (caja) #",
    trailerHelp: "The trailer number goes on the crossing papers.",
    note: "Note (optional)",
    reason: "Reason",
    reasonPh: "no trucks until Tuesday",
    back: "Back",
    sending: "Sending…",
    confirmAccept: "Confirm — we'll take it",
    confirmDecline: "Confirm decline",
    counter: "Counter-offer",
    counterTitle: "Your rate — dispatch answers here",
    yourRate: (cur: string) => `Your rate (${cur})`,
    sendCounter: "Send counter-offer",
    counterPending: (rate: string) => `Your counter-offer of ${rate} is with dispatch. You can still accept the rate above.`,
    counterAccepted: "Dispatch accepted your rate — confirm with your driver below.",
    counterDeclined: "Dispatch can't do your rate — the offer stands as above.",
  },
  es: {
    offer: "oferta de carga",
    leg: { mx: "Tramo México", ca: "Tramo Canadá", crossing: "Cruce fronterizo", us: "Tramo EE. UU.", domestic: "Nacional", equipment_move: "Movimiento de equipo" } as Record<string, string>,
    openUntil: "Abierta hasta",
    accepted: "Aceptada",
    declined: "Rechazada",
    expired: "Vencida",
    withdrawn: "Retirada",
    rateTbc: "Tarifa por confirmar",
    pickup: "Recoger",
    delivery: "Entregar",
    asap: "Lo antes posible",
    by: "a más tardar",
    pickupNo: "# de recolección",
    deliveryNo: "# de entrega",
    instructions: "Instrucciones",
    equipment: "Equipo",
    reference: "Referencia",
    leg_: "tramo",
    commodity: "Mercancía",
    pieces: "Piezas",
    weight: "Peso",
    hazmat: "Material peligroso",
    cargo: "Carga",
    fromDispatch: "Mensaje de despacho",
    thanks: "Gracias — es suya.",
    acceptedBy: (who: string, when: string, driver: string, unit: string | null, caja: string | null) => `Aceptada por ${who} el ${when}. Operador ${driver}${unit ? `, unidad ${unit}` : ""}${caja ? `, caja ${caja}` : ""}. Despacho enviará los detalles de la recolección.`,
    closed: "Esta oferta está cerrada.",
    expiredText: "Pasó la hora límite. Llame a despacho si todavía puede cubrirla.",
    declinedBy: (who: string) => `Rechazada por ${who}.`,
    withdrawnText: "Despacho la retiró.",
    switchTo: "View in English",
    canYou: (c: string) => `${c}, ¿puede cubrir esta carga?`,
    yes: "Sí, acepto",
    no: "No, rechazo",
    whoDrives: "Aceptar — ¿quién maneja?",
    why: "Rechazar — ¿por qué?",
    yourName: "Su nombre",
    driverName: "Nombre del operador",
    driverPhone: "Teléfono del operador",
    unit: "# de unidad",
    plates: "Placas de la unidad",
    trailer: "# de caja",
    trailerHelp: "El número de caja va en los papeles del cruce.",
    note: "Nota (opcional)",
    reason: "Motivo",
    reasonPh: "sin unidades hasta el martes",
    back: "Atrás",
    sending: "Enviando…",
    confirmAccept: "Confirmar — la tomamos",
    confirmDecline: "Confirmar rechazo",
    counter: "Contraoferta",
    counterTitle: "Su tarifa — despacho responde aquí",
    yourRate: (cur: string) => `Su tarifa (${cur})`,
    sendCounter: "Enviar contraoferta",
    counterPending: (rate: string) => `Su contraoferta de ${rate} está con despacho. Todavía puede aceptar la tarifa de arriba.`,
    counterAccepted: "Despacho aceptó su tarifa — confirme con su operador abajo.",
    counterDeclined: "Despacho no puede pagar su tarifa — la oferta sigue como arriba.",
  },
};
export type TenderCopy = (typeof TENDER_COPY)["en"];

/** Spanish for a Mexican carrier unless the link asks for English (and the other way round). */
export function tenderLang(carrierCountry: string | null | undefined, asked?: string | null): Lang {
  if (asked === "es" || asked === "en") return asked;
  return (carrierCountry ?? "").toUpperCase() === "MX" ? "es" : "en";
}
